apiVersion: apps/v1
kind: Deployment
metadata:
  name: style-transfer
  namespace: default
  labels:
    k8s-app: style-transfer
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: style-transfer
  template:
    metadata:
      name: style-transfer
      labels:
        k8s-app: style-transfer
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: style-transfer
          image: amidadragon/style-transfer:latest
          securityContext:
            privileged: false
          volumeMounts:
            - mountPath: "/app/model"
              name: task-pv-storage
